// Курированное тематическое ядро словаря A1–B1.
//
// Авторский список: отбор слов и русские переводы — вручную, по таксономии
// уровней (A1 выживание / A2 общение / B1 порог). Существительные — с артиклем
// (le/la/l'/les), глаголы — в инфинитиве. Русский перевод — одно чистое
// значение, максимум два через «; », когда оба реально базовые.
//
// Сборка: node scripts/build-themed-dict.mjs (сверяет каждое слово с WikDict,
// сортирует внутри темы по частотности, пишет public/dict/fr-ru-themed.json).
// Правим здесь — точечно; порядок слов внутри темы не важен (сортирует сборка).

export const THEMES = [
  // ─────────────────────────── A1 ───────────────────────────
  {
    theme: 'Приветствия и вежливость',
    level: 'A1',
    words: [
      ['bonjour', 'здравствуйте'],
      ['bonsoir', 'добрый вечер'],
      ['salut', 'привет'],
      ['au revoir', 'до свидания'],
      ['à bientôt', 'до скорого'],
      ['à demain', 'до завтра'],
      ['à tout à l\'heure', 'до скорого (сегодня)'],
      ['bonne nuit', 'спокойной ночи'],
      ['bonne journée', 'хорошего дня'],
      ['merci', 'спасибо'],
      ['merci beaucoup', 'большое спасибо'],
      ['s\'il vous plaît', 'пожалуйста (просьба)'],
      ['de rien', 'не за что'],
      ['je vous en prie', 'пожалуйста; не за что'],
      ['pardon', 'извините'],
      ['excusez-moi', 'простите'],
      ['désolé', 'сожалею'],
      ['oui', 'да'],
      ['non', 'нет'],
      ['peut-être', 'может быть'],
      ['d\'accord', 'согласен; договорились'],
      ['monsieur', 'господин'],
      ['madame', 'госпожа'],
      ['bienvenue', 'добро пожаловать'],
      ['enchanté', 'очень приятно'],
      ['comment allez-vous', 'как вы поживаете'],
      ['ça va', 'как дела; нормально'],
    ],
  },
  {
    theme: 'Знакомство и личные данные',
    level: 'A1',
    words: [
      ['le nom', 'фамилия; имя'],
      ['le prénom', 'имя'],
      ['s\'appeler', 'зваться'],
      ['se présenter', 'представляться'],
      ['l\'âge', 'возраст'],
      ['la nationalité', 'национальность'],
      ['le pays', 'страна'],
      ['l\'adresse', 'адрес'],
      ['la rue', 'улица'],
      ['le téléphone', 'телефон'],
      ['le numéro', 'номер'],
      ['l\'e-mail', 'электронная почта'],
      ['français', 'французский'],
      ['française', 'француженка; французская'],
      ['russe', 'русский'],
      ['anglais', 'английский'],
      ['américain', 'американец; американский'],
      ['espagnol', 'испанец; испанский'],
      ['allemand', 'немец; немецкий'],
      ['italien', 'итальянец; итальянский'],
      ['parler', 'говорить'],
      ['comprendre', 'понимать'],
      ['connaître', 'быть знакомым'],
      ['rencontrer', 'встречать'],
      ['épeler', 'произносить по буквам'],
      ['habiter', 'жить; проживать'],
      ['venir', 'приходить; приезжать'],
      ['être né', 'родиться'],
      ['marié', 'женатый; замужняя'],
      ['célibataire', 'холостой; незамужняя'],
    ],
  },
  {
    theme: 'Семья и люди',
    level: 'A1',
    words: [
      ['la famille', 'семья'],
      ['les parents', 'родители'],
      ['la mère', 'мать'],
      ['le père', 'отец'],
      ['la maman', 'мама'],
      ['le papa', 'папа'],
      ['le fils', 'сын'],
      ['la fille', 'дочь; девочка'],
      ['le frère', 'брат'],
      ['la sœur', 'сестра'],
      ['le grand-père', 'дедушка'],
      ['la grand-mère', 'бабушка'],
      ['les grands-parents', 'бабушка и дедушка'],
      ['l\'oncle', 'дядя'],
      ['la tante', 'тётя'],
      ['le cousin', 'двоюродный брат'],
      ['la cousine', 'двоюродная сестра'],
      ['le neveu', 'племянник'],
      ['la nièce', 'племянница'],
      ['le mari', 'муж'],
      ['la femme', 'жена; женщина'],
      ['l\'enfant', 'ребёнок'],
      ['le bébé', 'младенец'],
      ['l\'homme', 'мужчина; человек'],
      ['la personne', 'человек; лицо'],
      ['les gens', 'люди'],
      ['l\'ami', 'друг'],
      ['l\'amie', 'подруга'],
      ['le voisin', 'сосед'],
      ['la voisine', 'соседка'],
      ['le monsieur', 'мужчина; господин'],
      ['la dame', 'женщина; дама'],
      ['le garçon', 'мальчик'],
      ['le copain', 'приятель; парень'],
      ['la copine', 'подруга; девушка'],
    ],
  },
  {
    theme: 'Числа, даты и время',
    level: 'A1',
    words: [
      ['zéro', 'ноль'],
      ['un', 'один'],
      ['deux', 'два'],
      ['trois', 'три'],
      ['quatre', 'четыре'],
      ['cinq', 'пять'],
      ['six', 'шесть'],
      ['sept', 'семь'],
      ['huit', 'восемь'],
      ['neuf', 'девять'],
      ['dix', 'десять'],
      ['onze', 'одиннадцать'],
      ['douze', 'двенадцать'],
      ['vingt', 'двадцать'],
      ['trente', 'тридцать'],
      ['quarante', 'сорок'],
      ['cinquante', 'пятьдесят'],
      ['cent', 'сто'],
      ['mille', 'тысяча'],
      ['premier', 'первый'],
      ['deuxième', 'второй'],
      ['dernier', 'последний'],
      ['le jour', 'день'],
      ['la semaine', 'неделя'],
      ['le mois', 'месяц'],
      ['l\'année', 'год'],
      ['aujourd\'hui', 'сегодня'],
      ['demain', 'завтра'],
      ['hier', 'вчера'],
      ['maintenant', 'сейчас'],
      ['lundi', 'понедельник'],
      ['mardi', 'вторник'],
      ['mercredi', 'среда'],
      ['jeudi', 'четверг'],
      ['vendredi', 'пятница'],
      ['samedi', 'суббота'],
      ['dimanche', 'воскресенье'],
      ['janvier', 'январь'],
      ['février', 'февраль'],
      ['mars', 'март'],
      ['avril', 'апрель'],
      ['mai', 'май'],
      ['juin', 'июнь'],
      ['juillet', 'июль'],
      ['août', 'август'],
      ['septembre', 'сентябрь'],
      ['octobre', 'октябрь'],
      ['novembre', 'ноябрь'],
      ['décembre', 'декабрь'],
      ['l\'heure', 'час; время'],
      ['la minute', 'минута'],
      ['le matin', 'утро'],
      ['le midi', 'полдень'],
      ['l\'après-midi', 'вторая половина дня'],
      ['le soir', 'вечер'],
      ['la nuit', 'ночь'],
      ['tôt', 'рано'],
      ['tard', 'поздно'],
    ],
  },
  {
    theme: 'Еда и напитки',
    level: 'A1',
    words: [
      ['la nourriture', 'еда'],
      ['le repas', 'приём пищи'],
      ['le petit-déjeuner', 'завтрак'],
      ['le déjeuner', 'обед'],
      ['le dîner', 'ужин'],
      ['le pain', 'хлеб'],
      ['le beurre', 'масло сливочное'],
      ['le fromage', 'сыр'],
      ['l\'œuf', 'яйцо'],
      ['le lait', 'молоко'],
      ['la viande', 'мясо'],
      ['le poisson', 'рыба'],
      ['le poulet', 'курица'],
      ['le jambon', 'ветчина'],
      ['le riz', 'рис'],
      ['les pâtes', 'макароны'],
      ['la pomme de terre', 'картофель'],
      ['la soupe', 'суп'],
      ['la salade', 'салат'],
      ['le légume', 'овощ'],
      ['le fruit', 'фрукт'],
      ['la pomme', 'яблоко'],
      ['la banane', 'банан'],
      ['l\'orange', 'апельсин'],
      ['la fraise', 'клубника'],
      ['la tomate', 'помидор'],
      ['la carotte', 'морковь'],
      ['l\'oignon', 'лук'],
      ['le sel', 'соль'],
      ['le poivre', 'перец'],
      ['le sucre', 'сахар'],
      ['l\'huile', 'масло растительное'],
      ['le gâteau', 'торт; пирожное'],
      ['le chocolat', 'шоколад'],
      ['la glace', 'мороженое; лёд'],
      ['l\'eau', 'вода'],
      ['le café', 'кофе; кафе'],
      ['le thé', 'чай'],
      ['le jus', 'сок'],
      ['le vin', 'вино'],
      ['la bière', 'пиво'],
      ['la boisson', 'напиток'],
      ['manger', 'есть'],
      ['boire', 'пить'],
      ['cuisiner', 'готовить'],
      ['goûter', 'пробовать на вкус'],
      ['avoir faim', 'быть голодным'],
      ['avoir soif', 'хотеть пить'],
      ['le restaurant', 'ресторан'],
      ['la carte', 'меню; карта'],
      ['l\'addition', 'счёт в кафе'],
      ['le serveur', 'официант'],
      ['commander', 'заказывать'],
      ['délicieux', 'вкусный'],
    ],
  },
  {
    theme: 'Одежда и цвета',
    level: 'A1',
    words: [
      ['les vêtements', 'одежда'],
      ['la chemise', 'рубашка'],
      ['le pantalon', 'брюки'],
      ['la robe', 'платье'],
      ['la jupe', 'юбка'],
      ['le pull', 'свитер'],
      ['le manteau', 'пальто'],
      ['la veste', 'куртка; пиджак'],
      ['le blouson', 'куртка'],
      ['le tee-shirt', 'футболка'],
      ['les chaussures', 'обувь'],
      ['les chaussettes', 'носки'],
      ['le chapeau', 'шляпа'],
      ['le bonnet', 'шапка'],
      ['l\'écharpe', 'шарф'],
      ['les gants', 'перчатки'],
      ['la ceinture', 'ремень'],
      ['le sac', 'сумка'],
      ['les lunettes', 'очки'],
      ['le maillot de bain', 'купальник; плавки'],
      ['porter', 'носить одежду'],
      ['s\'habiller', 'одеваться'],
      ['la taille', 'размер; рост'],
      ['la couleur', 'цвет'],
      ['blanc', 'белый'],
      ['noir', 'чёрный'],
      ['rouge', 'красный'],
      ['bleu', 'синий'],
      ['vert', 'зелёный'],
      ['jaune', 'жёлтый'],
      ['gris', 'серый'],
      ['marron', 'коричневый'],
      ['rose', 'розовый'],
      ['orange', 'оранжевый'],
      ['violet', 'фиолетовый'],
      ['clair', 'светлый'],
      ['foncé', 'тёмный'],
    ],
  },
  {
    theme: 'Дом и мебель',
    level: 'A1',
    words: [
      ['la maison', 'дом'],
      ['l\'appartement', 'квартира'],
      ['l\'immeuble', 'многоквартирный дом'],
      ['l\'étage', 'этаж'],
      ['la pièce', 'комната'],
      ['la chambre', 'спальня'],
      ['le salon', 'гостиная'],
      ['la cuisine', 'кухня'],
      ['la salle de bains', 'ванная'],
      ['les toilettes', 'туалет'],
      ['l\'entrée', 'прихожая; вход'],
      ['le couloir', 'коридор'],
      ['le balcon', 'балкон'],
      ['le jardin', 'сад'],
      ['le garage', 'гараж'],
      ['la porte', 'дверь'],
      ['la fenêtre', 'окно'],
      ['le mur', 'стена'],
      ['le sol', 'пол'],
      ['le plafond', 'потолок'],
      ['l\'escalier', 'лестница'],
      ['le meuble', 'предмет мебели'],
      ['la table', 'стол'],
      ['la chaise', 'стул'],
      ['le fauteuil', 'кресло'],
      ['le canapé', 'диван'],
      ['le lit', 'кровать'],
      ['l\'armoire', 'шкаф'],
      ['l\'étagère', 'полка'],
      ['le bureau', 'письменный стол; кабинет'],
      ['la lampe', 'лампа'],
      ['le tapis', 'ковёр'],
      ['le rideau', 'штора'],
      ['le miroir', 'зеркало'],
      ['le frigo', 'холодильник'],
      ['le four', 'духовка'],
      ['la cuisinière', 'плита'],
      ['le lave-linge', 'стиральная машина'],
      ['la télévision', 'телевизор'],
      ['la clé', 'ключ'],
      ['louer', 'снимать; сдавать'],
      ['déménager', 'переезжать'],
      ['ranger', 'убирать; раскладывать'],
      ['nettoyer', 'чистить; мыть'],
    ],
  },
  {
    theme: 'Город, магазины, транспорт',
    level: 'A1',
    words: [
      ['la ville', 'город'],
      ['le village', 'деревня'],
      ['le centre-ville', 'центр города'],
      ['le quartier', 'район'],
      ['la rue', 'улица'],
      ['l\'avenue', 'проспект'],
      ['la place', 'площадь'],
      ['le pont', 'мост'],
      ['le parc', 'парк'],
      ['la gare', 'вокзал'],
      ['l\'aéroport', 'аэропорт'],
      ['la station', 'станция'],
      ['l\'arrêt', 'остановка'],
      ['le magasin', 'магазин'],
      ['la boutique', 'магазинчик'],
      ['le supermarché', 'супермаркет'],
      ['le marché', 'рынок'],
      ['la boulangerie', 'булочная'],
      ['la pharmacie', 'аптека'],
      ['la banque', 'банк'],
      ['la poste', 'почта'],
      ['l\'hôpital', 'больница'],
      ['l\'école', 'школа'],
      ['l\'église', 'церковь'],
      ['le musée', 'музей'],
      ['le cinéma', 'кинотеатр'],
      ['l\'hôtel', 'гостиница'],
      ['la bibliothèque', 'библиотека'],
      ['le bureau de poste', 'почтовое отделение'],
      ['la voiture', 'машина'],
      ['le bus', 'автобус'],
      ['le métro', 'метро'],
      ['le train', 'поезд'],
      ['le tram', 'трамвай'],
      ['le taxi', 'такси'],
      ['le vélo', 'велосипед'],
      ['la moto', 'мотоцикл'],
      ['l\'avion', 'самолёт'],
      ['le bateau', 'лодка; корабль'],
      ['le billet', 'билет'],
      ['le plan', 'план; карта города'],
      ['aller', 'идти; ехать'],
      ['marcher', 'идти пешком'],
      ['conduire', 'вести машину'],
      ['prendre', 'брать; садиться на транспорт'],
      ['tourner', 'поворачивать'],
      ['continuer', 'продолжать'],
      ['traverser', 'переходить'],
      ['à gauche', 'налево'],
      ['à droite', 'направо'],
      ['tout droit', 'прямо'],
      ['près', 'близко'],
      ['loin', 'далеко'],
      ['acheter', 'покупать'],
      ['payer', 'платить'],
      ['coûter', 'стоить'],
      ['l\'argent', 'деньги'],
      ['le prix', 'цена'],
      ['la monnaie', 'сдача; мелочь'],
      ['cher', 'дорогой'],
      ['gratuit', 'бесплатный'],
    ],
  },
  {
    theme: 'Погода и природа',
    level: 'A1',
    words: [
      ['le temps', 'погода; время'],
      ['il fait beau', 'хорошая погода'],
      ['il fait mauvais', 'плохая погода'],
      ['il fait chaud', 'жарко'],
      ['il fait froid', 'холодно'],
      ['le soleil', 'солнце'],
      ['la pluie', 'дождь'],
      ['la neige', 'снег'],
      ['le vent', 'ветер'],
      ['le nuage', 'облако'],
      ['le ciel', 'небо'],
      ['l\'orage', 'гроза'],
      ['le brouillard', 'туман'],
      ['la glace', 'лёд'],
      ['pleuvoir', 'идти о дожде'],
      ['neiger', 'идти о снеге'],
      ['ensoleillé', 'солнечный'],
      ['nuageux', 'облачный'],
      ['humide', 'влажный'],
      ['sec', 'сухой'],
      ['la température', 'температура'],
      ['le degré', 'градус'],
      ['la saison', 'время года'],
      ['le printemps', 'весна'],
      ['l\'été', 'лето'],
      ['l\'automne', 'осень'],
      ['l\'hiver', 'зима'],
      ['la nature', 'природа'],
      ['la mer', 'море'],
      ['la montagne', 'гора'],
      ['la forêt', 'лес'],
      ['le lac', 'озеро'],
      ['la rivière', 'река'],
      ['la plage', 'пляж'],
      ['la campagne', 'сельская местность'],
      ['l\'arbre', 'дерево'],
      ['la fleur', 'цветок'],
      ['l\'herbe', 'трава'],
      ['la terre', 'земля'],
      ['la pierre', 'камень'],
    ],
  },
  {
    theme: 'Тело и здоровье',
    level: 'A1',
    words: [
      ['le corps', 'тело'],
      ['la tête', 'голова'],
      ['le visage', 'лицо'],
      ['le cheveu', 'волос'],
      ['l\'œil', 'глаз'],
      ['les yeux', 'глаза'],
      ['le nez', 'нос'],
      ['la bouche', 'рот'],
      ['l\'oreille', 'ухо'],
      ['la dent', 'зуб'],
      ['le cou', 'шея'],
      ['l\'épaule', 'плечо'],
      ['le bras', 'рука (от плеча)'],
      ['la main', 'кисть руки'],
      ['le doigt', 'палец'],
      ['le dos', 'спина'],
      ['le ventre', 'живот'],
      ['la jambe', 'нога'],
      ['le pied', 'ступня'],
      ['le genou', 'колено'],
      ['le cœur', 'сердце'],
      ['la peau', 'кожа'],
      ['la santé', 'здоровье'],
      ['le médecin', 'врач'],
      ['le dentiste', 'стоматолог'],
      ['la maladie', 'болезнь'],
      ['la douleur', 'боль'],
      ['la fièvre', 'температура; жар'],
      ['le rhume', 'насморк; простуда'],
      ['la grippe', 'грипп'],
      ['le médicament', 'лекарство'],
      ['la pharmacie', 'аптека'],
      ['être malade', 'болеть'],
      ['avoir mal', 'испытывать боль'],
      ['tomber', 'падать'],
      ['se sentir', 'чувствовать себя'],
      ['aller mieux', 'идти на поправку'],
      ['fatigué', 'усталый'],
      ['en forme', 'в хорошей форме'],
    ],
  },
  {
    theme: 'Работа и профессии',
    level: 'A1',
    words: [
      ['le travail', 'работа'],
      ['le métier', 'профессия'],
      ['la profession', 'профессия'],
      ['l\'entreprise', 'предприятие; компания'],
      ['le bureau', 'офис'],
      ['l\'usine', 'завод'],
      ['le collègue', 'коллега'],
      ['le patron', 'начальник'],
      ['le salaire', 'зарплата'],
      ['le médecin', 'врач'],
      ['l\'infirmier', 'медбрат'],
      ['l\'infirmière', 'медсестра'],
      ['le professeur', 'преподаватель'],
      ['l\'instituteur', 'учитель начальных классов'],
      ['l\'étudiant', 'студент'],
      ['l\'ingénieur', 'инженер'],
      ['l\'avocat', 'адвокат'],
      ['le vendeur', 'продавец'],
      ['la vendeuse', 'продавщица'],
      ['le boulanger', 'пекарь'],
      ['le cuisinier', 'повар'],
      ['le serveur', 'официант'],
      ['le chauffeur', 'водитель'],
      ['le policier', 'полицейский'],
      ['le pompier', 'пожарный'],
      ['le facteur', 'почтальон'],
      ['le coiffeur', 'парикмахер'],
      ['le journaliste', 'журналист'],
      ['l\'artiste', 'художник; артист'],
      ['le musicien', 'музыкант'],
      ['l\'agriculteur', 'фермер'],
      ['le secrétaire', 'секретарь'],
      ['le directeur', 'директор'],
      ['travailler', 'работать'],
      ['gagner', 'зарабатывать; выигрывать'],
      ['chercher un emploi', 'искать работу'],
      ['être au chômage', 'быть безработным'],
      ['à la retraite', 'на пенсии'],
    ],
  },
  {
    theme: 'Хобби и досуг',
    level: 'A1',
    words: [
      ['le loisir', 'досуг'],
      ['le temps libre', 'свободное время'],
      ['le sport', 'спорт'],
      ['le football', 'футбол'],
      ['le tennis', 'теннис'],
      ['la natation', 'плавание'],
      ['le vélo', 'велоспорт'],
      ['la course', 'бег'],
      ['la danse', 'танцы'],
      ['la musique', 'музыка'],
      ['la chanson', 'песня'],
      ['le piano', 'пианино'],
      ['la guitare', 'гитара'],
      ['le cinéma', 'кино'],
      ['le film', 'фильм'],
      ['le théâtre', 'театр'],
      ['le livre', 'книга'],
      ['la lecture', 'чтение'],
      ['le jeu', 'игра'],
      ['la photo', 'фотография'],
      ['le voyage', 'путешествие'],
      ['la promenade', 'прогулка'],
      ['la fête', 'праздник; вечеринка'],
      ['jouer', 'играть'],
      ['chanter', 'петь'],
      ['danser', 'танцевать'],
      ['lire', 'читать'],
      ['écouter', 'слушать'],
      ['regarder', 'смотреть'],
      ['nager', 'плавать'],
      ['courir', 'бегать'],
      ['dessiner', 'рисовать'],
      ['voyager', 'путешествовать'],
      ['se promener', 'гулять'],
      ['faire du sport', 'заниматься спортом'],
      ['aimer', 'любить; нравиться'],
      ['préférer', 'предпочитать'],
      ['détester', 'ненавидеть'],
    ],
  },
  {
    theme: 'Частые глаголы',
    level: 'A1',
    words: [
      ['être', 'быть'],
      ['avoir', 'иметь'],
      ['faire', 'делать'],
      ['aller', 'идти; ехать'],
      ['venir', 'приходить'],
      ['pouvoir', 'мочь'],
      ['vouloir', 'хотеть'],
      ['devoir', 'быть должным'],
      ['savoir', 'знать'],
      ['dire', 'сказать'],
      ['voir', 'видеть'],
      ['prendre', 'брать'],
      ['donner', 'давать'],
      ['mettre', 'класть; надевать'],
      ['trouver', 'находить'],
      ['penser', 'думать'],
      ['croire', 'верить; полагать'],
      ['demander', 'спрашивать; просить'],
      ['répondre', 'отвечать'],
      ['parler', 'говорить'],
      ['aimer', 'любить'],
      ['travailler', 'работать'],
      ['habiter', 'жить'],
      ['rester', 'оставаться'],
      ['passer', 'проходить; проводить'],
      ['arriver', 'прибывать; случаться'],
      ['partir', 'уходить; уезжать'],
      ['sortir', 'выходить'],
      ['entrer', 'входить'],
      ['monter', 'подниматься'],
      ['descendre', 'спускаться'],
      ['ouvrir', 'открывать'],
      ['fermer', 'закрывать'],
      ['commencer', 'начинать'],
      ['finir', 'заканчивать'],
      ['attendre', 'ждать'],
      ['appeler', 'звать; звонить'],
      ['acheter', 'покупать'],
      ['payer', 'платить'],
      ['manger', 'есть'],
      ['boire', 'пить'],
      ['dormir', 'спать'],
      ['vivre', 'жить'],
      ['écrire', 'писать'],
      ['lire', 'читать'],
      ['comprendre', 'понимать'],
      ['apprendre', 'учить; узнавать'],
      ['aider', 'помогать'],
      ['jouer', 'играть'],
      ['écouter', 'слушать'],
      ['entendre', 'слышать'],
      ['sembler', 'казаться'],
      ['devenir', 'становиться'],
      ['tenir', 'держать'],
      ['porter', 'нести; носить'],
      ['montrer', 'показывать'],
      ['chercher', 'искать'],
      ['utiliser', 'использовать'],
      ['essayer', 'пробовать; примерять'],
      ['oublier', 'забывать'],
      ['se rappeler', 'вспоминать'],
      ['choisir', 'выбирать'],
      ['changer', 'менять'],
      ['perdre', 'терять'],
    ],
  },
  {
    theme: 'Служебные слова и связки',
    level: 'A1',
    words: [
      ['et', 'и'],
      ['ou', 'или'],
      ['mais', 'но'],
      ['donc', 'значит; поэтому'],
      ['parce que', 'потому что'],
      ['car', 'так как'],
      ['pour', 'для; чтобы'],
      ['sans', 'без'],
      ['avec', 'с'],
      ['aussi', 'тоже'],
      ['très', 'очень'],
      ['trop', 'слишком'],
      ['beaucoup', 'много'],
      ['un peu', 'немного'],
      ['assez', 'достаточно; довольно'],
      ['plus', 'больше'],
      ['moins', 'меньше'],
      ['bien', 'хорошо'],
      ['mal', 'плохо'],
      ['toujours', 'всегда'],
      ['souvent', 'часто'],
      ['parfois', 'иногда'],
      ['jamais', 'никогда'],
      ['déjà', 'уже'],
      ['encore', 'ещё'],
      ['maintenant', 'сейчас'],
      ['ici', 'здесь'],
      ['là', 'там'],
      ['là-bas', 'вон там'],
      ['dedans', 'внутри'],
      ['dehors', 'снаружи'],
      ['dessus', 'сверху'],
      ['dessous', 'снизу'],
      ['avant', 'до; перед'],
      ['après', 'после'],
      ['pendant', 'во время'],
      ['depuis', 'с; в течение'],
      ['bientôt', 'скоро'],
      ['dans', 'в'],
      ['sur', 'на'],
      ['sous', 'под'],
      ['devant', 'перед'],
      ['derrière', 'позади'],
      ['entre', 'между'],
      ['chez', 'у'],
      ['vers', 'к; около'],
      ['quel', 'какой'],
      ['qui', 'кто'],
      ['que', 'что'],
      ['quoi', 'что'],
      ['où', 'где; куда'],
      ['quand', 'когда'],
      ['comment', 'как'],
      ['pourquoi', 'почему'],
      ['combien', 'сколько'],
      ['oui', 'да'],
      ['non', 'нет'],
      ['peut-être', 'может быть'],
      ['si', 'если; да (в ответ на отрицание)'],
    ],
  },

  // ─────────────────────────── A2 ───────────────────────────
  {
    theme: 'Характер и внешность',
    level: 'A2',
    words: [
      ['le caractère', 'характер'],
      ['la personnalité', 'личность'],
      ['gentil', 'добрый; милый'],
      ['méchant', 'злой'],
      ['sympathique', 'приятный; симпатичный'],
      ['aimable', 'любезный'],
      ['poli', 'вежливый'],
      ['timide', 'застенчивый'],
      ['sérieux', 'серьёзный'],
      ['drôle', 'смешной'],
      ['calme', 'спокойный'],
      ['nerveux', 'нервный'],
      ['patient', 'терпеливый'],
      ['paresseux', 'ленивый'],
      ['travailleur', 'трудолюбивый'],
      ['honnête', 'честный'],
      ['généreux', 'щедрый'],
      ['égoïste', 'эгоистичный'],
      ['courageux', 'смелый'],
      ['intelligent', 'умный'],
      ['bête', 'глупый'],
      ['curieux', 'любопытный'],
      ['jeune', 'молодой'],
      ['vieux', 'старый'],
      ['beau', 'красивый'],
      ['joli', 'хорошенький'],
      ['laid', 'некрасивый'],
      ['mignon', 'миловидный'],
      ['grand', 'высокий; большой'],
      ['petit', 'маленький'],
      ['gros', 'толстый'],
      ['mince', 'худой; стройный'],
      ['fort', 'сильный'],
      ['faible', 'слабый'],
      ['blond', 'светловолосый'],
      ['brun', 'темноволосый'],
      ['roux', 'рыжий'],
      ['chauve', 'лысый'],
      ['la barbe', 'борода'],
      ['la moustache', 'усы'],
      ['ressembler', 'быть похожим'],
      ['avoir l\'air', 'выглядеть'],
    ],
  },
  {
    theme: 'Покупки',
    level: 'A2',
    words: [
      ['le client', 'покупатель; клиент'],
      ['la cliente', 'покупательница'],
      ['le rayon', 'отдел в магазине'],
      ['la caisse', 'касса'],
      ['le caddie', 'тележка'],
      ['le panier', 'корзина'],
      ['la vitrine', 'витрина'],
      ['la cabine d\'essayage', 'примерочная'],
      ['la pointure', 'размер обуви'],
      ['la réduction', 'скидка'],
      ['les soldes', 'распродажа'],
      ['la promotion', 'акция; скидка'],
      ['le reçu', 'чек'],
      ['le ticket', 'чек; билетик'],
      ['la carte bancaire', 'банковская карта'],
      ['les espèces', 'наличные'],
      ['la livraison', 'доставка'],
      ['la garantie', 'гарантия'],
      ['l\'échange', 'обмен'],
      ['le remboursement', 'возврат денег'],
      ['la qualité', 'качество'],
      ['la marque', 'марка; бренд'],
      ['essayer', 'примерять'],
      ['choisir', 'выбирать'],
      ['coûter', 'стоить'],
      ['dépenser', 'тратить'],
      ['économiser', 'экономить'],
      ['rendre', 'возвращать'],
      ['emballer', 'упаковывать'],
      ['bon marché', 'дешёвый'],
      ['neuf', 'новый'],
      ['d\'occasion', 'подержанный'],
      ['la boulangerie', 'булочная'],
      ['la boucherie', 'мясная лавка'],
      ['l\'épicerie', 'продуктовый магазин'],
      ['la librairie', 'книжный магазин'],
      ['le centre commercial', 'торговый центр'],
    ],
  },
  {
    theme: 'Здоровье и врач',
    level: 'A2',
    words: [
      ['le cabinet', 'кабинет врача'],
      ['le rendez-vous', 'приём; встреча'],
      ['l\'ordonnance', 'рецепт врача'],
      ['la consultation', 'консультация'],
      ['l\'urgence', 'неотложная помощь'],
      ['la pharmacie', 'аптека'],
      ['le comprimé', 'таблетка'],
      ['le sirop', 'сироп'],
      ['la piqûre', 'укол'],
      ['le vaccin', 'прививка'],
      ['le pansement', 'пластырь; повязка'],
      ['la blessure', 'рана'],
      ['la brûlure', 'ожог'],
      ['le symptôme', 'симптом'],
      ['la toux', 'кашель'],
      ['le mal de tête', 'головная боль'],
      ['le mal de gorge', 'боль в горле'],
      ['le mal de ventre', 'боль в животе'],
      ['la nausée', 'тошнота'],
      ['l\'allergie', 'аллергия'],
      ['la tension', 'давление'],
      ['le poids', 'вес'],
      ['le régime', 'диета'],
      ['tousser', 'кашлять'],
      ['éternuer', 'чихать'],
      ['saigner', 'кровоточить'],
      ['guérir', 'выздоравливать'],
      ['soigner', 'лечить'],
      ['se reposer', 'отдыхать'],
      ['respirer', 'дышать'],
      ['grave', 'серьёзный; тяжёлый'],
      ['enceinte', 'беременная'],
      ['en bonne santé', 'здоровый'],
    ],
  },
  {
    theme: 'Путешествия',
    level: 'A2',
    words: [
      ['le voyage', 'путешествие'],
      ['les vacances', 'отпуск; каникулы'],
      ['le tourisme', 'туризм'],
      ['le touriste', 'турист'],
      ['la valise', 'чемодан'],
      ['le sac à dos', 'рюкзак'],
      ['le passeport', 'паспорт'],
      ['le visa', 'виза'],
      ['la frontière', 'граница'],
      ['la douane', 'таможня'],
      ['le vol', 'рейс; кража'],
      ['le départ', 'отправление'],
      ['l\'arrivée', 'прибытие'],
      ['le retard', 'опоздание'],
      ['la correspondance', 'пересадка'],
      ['le quai', 'платформа'],
      ['la réservation', 'бронирование'],
      ['la chambre d\'hôtel', 'номер в отеле'],
      ['la réception', 'ресепшн'],
      ['la clé', 'ключ'],
      ['l\'auberge de jeunesse', 'хостел'],
      ['le camping', 'кемпинг'],
      ['la carte postale', 'открытка'],
      ['le souvenir', 'сувенир; воспоминание'],
      ['l\'office de tourisme', 'туристический офис'],
      ['le guide', 'гид; путеводитель'],
      ['l\'itinéraire', 'маршрут'],
      ['la carte', 'карта'],
      ['réserver', 'бронировать'],
      ['annuler', 'отменять'],
      ['partir en voyage', 'отправляться в путешествие'],
      ['visiter', 'посещать'],
      ['se perdre', 'заблудиться'],
      ['à l\'étranger', 'за границей'],
    ],
  },
  {
    theme: 'Распорядок дня и быт',
    level: 'A2',
    words: [
      ['la routine', 'распорядок; рутина'],
      ['l\'habitude', 'привычка'],
      ['se réveiller', 'просыпаться'],
      ['se lever', 'вставать'],
      ['se laver', 'мыться'],
      ['se doucher', 'принимать душ'],
      ['se brosser les dents', 'чистить зубы'],
      ['se coiffer', 'причёсываться'],
      ['se raser', 'бриться'],
      ['se maquiller', 'краситься'],
      ['s\'habiller', 'одеваться'],
      ['prendre le petit-déjeuner', 'завтракать'],
      ['aller au travail', 'ехать на работу'],
      ['rentrer', 'возвращаться домой'],
      ['se reposer', 'отдыхать'],
      ['se coucher', 'ложиться спать'],
      ['s\'endormir', 'засыпать'],
      ['le ménage', 'уборка'],
      ['la vaisselle', 'посуда; мытьё посуды'],
      ['la lessive', 'стирка'],
      ['le repassage', 'глажка'],
      ['les courses', 'покупки продуктов'],
      ['la poubelle', 'мусорное ведро'],
      ['l\'aspirateur', 'пылесос'],
      ['le balai', 'веник'],
      ['faire le lit', 'заправлять кровать'],
      ['faire la cuisine', 'готовить'],
      ['faire le ménage', 'убираться'],
      ['sortir la poubelle', 'выносить мусор'],
      ['arroser', 'поливать'],
      ['bricoler', 'мастерить'],
      ['jardiner', 'заниматься садом'],
      ['tôt le matin', 'рано утром'],
      ['toute la journée', 'весь день'],
    ],
  },
  {
    theme: 'Общение и связь',
    level: 'A2',
    words: [
      ['la conversation', 'разговор'],
      ['l\'appel', 'звонок'],
      ['le message', 'сообщение'],
      ['le texto', 'смс'],
      ['la lettre', 'письмо'],
      ['l\'enveloppe', 'конверт'],
      ['le timbre', 'марка'],
      ['le colis', 'посылка'],
      ['la boîte aux lettres', 'почтовый ящик'],
      ['le portable', 'мобильный телефон'],
      ['l\'ordinateur', 'компьютер'],
      ['l\'écran', 'экран'],
      ['le clavier', 'клавиатура'],
      ['le réseau', 'сеть'],
      ['le mot de passe', 'пароль'],
      ['le site', 'сайт'],
      ['le lien', 'ссылка'],
      ['la pièce jointe', 'вложение'],
      ['appeler', 'звонить'],
      ['rappeler', 'перезванивать'],
      ['raccrocher', 'вешать трубку'],
      ['décrocher', 'снимать трубку'],
      ['envoyer', 'отправлять'],
      ['recevoir', 'получать'],
      ['répondre', 'отвечать'],
      ['contacter', 'связываться'],
      ['prévenir', 'предупреждать'],
      ['discuter', 'обсуждать; беседовать'],
      ['expliquer', 'объяснять'],
      ['raconter', 'рассказывать'],
      ['inviter', 'приглашать'],
      ['remercier', 'благодарить'],
      ['s\'excuser', 'извиняться'],
      ['féliciter', 'поздравлять'],
      ['allô', 'алло'],
    ],
  },
  {
    theme: 'Чувства и эмоции',
    level: 'A2',
    words: [
      ['le sentiment', 'чувство'],
      ['l\'émotion', 'эмоция'],
      ['l\'humeur', 'настроение'],
      ['la joie', 'радость'],
      ['le bonheur', 'счастье'],
      ['la tristesse', 'грусть'],
      ['la peur', 'страх'],
      ['la colère', 'гнев'],
      ['la surprise', 'удивление'],
      ['la honte', 'стыд'],
      ['l\'amour', 'любовь'],
      ['la haine', 'ненависть'],
      ['l\'espoir', 'надежда'],
      ['l\'inquiétude', 'беспокойство'],
      ['le stress', 'стресс'],
      ['l\'ennui', 'скука'],
      ['heureux', 'счастливый'],
      ['content', 'довольный'],
      ['triste', 'грустный'],
      ['malheureux', 'несчастный'],
      ['fâché', 'рассерженный'],
      ['en colère', 'сердитый'],
      ['inquiet', 'обеспокоенный'],
      ['surpris', 'удивлённый'],
      ['déçu', 'разочарованный'],
      ['fier', 'гордый'],
      ['jaloux', 'ревнивый'],
      ['amoureux', 'влюблённый'],
      ['ému', 'растроганный'],
      ['soulager', 'приносить облегчение'],
      ['rire', 'смеяться'],
      ['pleurer', 'плакать'],
      ['sourire', 'улыбаться'],
      ['s\'inquiéter', 'беспокоиться'],
      ['se fâcher', 'сердиться'],
      ['avoir peur', 'бояться'],
      ['espérer', 'надеяться'],
      ['ressentir', 'испытывать'],
    ],
  },
  {
    theme: 'Природа и животные',
    level: 'A2',
    words: [
      ['l\'animal', 'животное'],
      ['le chien', 'собака'],
      ['le chat', 'кошка'],
      ['le cheval', 'лошадь'],
      ['la vache', 'корова'],
      ['le cochon', 'свинья'],
      ['le mouton', 'овца'],
      ['la chèvre', 'коза'],
      ['la poule', 'курица'],
      ['le coq', 'петух'],
      ['le canard', 'утка'],
      ['le lapin', 'кролик'],
      ['la souris', 'мышь'],
      ['l\'oiseau', 'птица'],
      ['le poisson', 'рыба'],
      ['l\'ours', 'медведь'],
      ['le loup', 'волк'],
      ['le renard', 'лиса'],
      ['le lion', 'лев'],
      ['l\'éléphant', 'слон'],
      ['le singe', 'обезьяна'],
      ['le serpent', 'змея'],
      ['la grenouille', 'лягушка'],
      ['l\'insecte', 'насекомое'],
      ['l\'abeille', 'пчела'],
      ['la mouche', 'муха'],
      ['le moustique', 'комар'],
      ['la fourmi', 'муравей'],
      ['le papillon', 'бабочка'],
      ['l\'araignée', 'паук'],
      ['la queue', 'хвост'],
      ['l\'aile', 'крыло'],
      ['la patte', 'лапа'],
      ['la plume', 'перо'],
      ['le poil', 'шерсть'],
      ['sauvage', 'дикий'],
      ['domestique', 'домашний'],
      ['aboyer', 'лаять'],
      ['voler', 'летать; красть'],
      ['mordre', 'кусать'],
    ],
  },
  {
    theme: 'Время: прошлое и будущее',
    level: 'A2',
    words: [
      ['le passé', 'прошлое'],
      ['le présent', 'настоящее'],
      ['le futur', 'будущее'],
      ['avant-hier', 'позавчера'],
      ['après-demain', 'послезавтра'],
      ['la veille', 'канун; накануне'],
      ['le lendemain', 'следующий день'],
      ['autrefois', 'раньше; в прежние времена'],
      ['récemment', 'недавно'],
      ['il y a', 'тому назад'],
      ['dernièrement', 'в последнее время'],
      ['tout à l\'heure', 'недавно; скоро'],
      ['à l\'époque', 'в то время'],
      ['de nos jours', 'в наши дни'],
      ['à l\'avenir', 'в будущем'],
      ['prochainement', 'в ближайшее время'],
      ['la semaine dernière', 'на прошлой неделе'],
      ['la semaine prochaine', 'на следующей неделе'],
      ['l\'an dernier', 'в прошлом году'],
      ['l\'an prochain', 'в следующем году'],
      ['le siècle', 'век'],
      ['la décennie', 'десятилетие'],
      ['le moment', 'момент'],
      ['l\'instant', 'мгновение'],
      ['la période', 'период'],
      ['l\'étape', 'этап'],
      ['soudain', 'вдруг'],
      ['aussitôt', 'сразу же'],
      ['enfin', 'наконец'],
      ['d\'abord', 'сначала'],
      ['ensuite', 'затем'],
      ['puis', 'потом'],
      ['tandis que', 'в то время как'],
      ['dès que', 'как только'],
    ],
  },

  // ─────────────────────────── B1 ───────────────────────────
  {
    theme: 'Общество и экология',
    level: 'B1',
    words: [
      ['la société', 'общество'],
      ['le citoyen', 'гражданин'],
      ['le droit', 'право'],
      ['le devoir', 'долг; обязанность'],
      ['l\'égalité', 'равенство'],
      ['la liberté', 'свобода'],
      ['la justice', 'справедливость; правосудие'],
      ['la loi', 'закон'],
      ['le gouvernement', 'правительство'],
      ['l\'État', 'государство'],
      ['la politique', 'политика'],
      ['l\'élection', 'выборы'],
      ['le vote', 'голосование'],
      ['la manifestation', 'демонстрация'],
      ['la grève', 'забастовка'],
      ['l\'impôt', 'налог'],
      ['la pauvreté', 'бедность'],
      ['le chômage', 'безработица'],
      ['l\'immigration', 'иммиграция'],
      ['la discrimination', 'дискриминация'],
      ['la solidarité', 'солидарность'],
      ['le bénévole', 'волонтёр'],
      ['l\'association', 'ассоциация; объединение'],
      ['l\'environnement', 'окружающая среда'],
      ['la pollution', 'загрязнение'],
      ['le réchauffement climatique', 'глобальное потепление'],
      ['le déchet', 'отход; мусор'],
      ['le recyclage', 'переработка'],
      ['le tri', 'сортировка'],
      ['l\'énergie', 'энергия'],
      ['la planète', 'планета'],
      ['la nature', 'природа'],
      ['l\'espèce', 'вид'],
      ['la forêt', 'лес'],
      ['polluer', 'загрязнять'],
      ['recycler', 'перерабатывать'],
      ['gaspiller', 'растрачивать; переводить'],
      ['protéger', 'защищать'],
      ['préserver', 'сохранять'],
      ['durable', 'устойчивый; экологичный'],
    ],
  },
  {
    theme: 'Культура и искусство',
    level: 'B1',
    words: [
      ['la culture', 'культура'],
      ['l\'art', 'искусство'],
      ['l\'artiste', 'художник; артист'],
      ['l\'œuvre', 'произведение'],
      ['le chef-d\'œuvre', 'шедевр'],
      ['la peinture', 'живопись; краска'],
      ['le tableau', 'картина'],
      ['le peintre', 'художник'],
      ['la sculpture', 'скульптура'],
      ['l\'exposition', 'выставка'],
      ['la galerie', 'галерея'],
      ['le spectacle', 'спектакль; шоу'],
      ['la pièce de théâtre', 'пьеса'],
      ['le comédien', 'актёр'],
      ['la scène', 'сцена'],
      ['le public', 'публика'],
      ['le roman', 'роман'],
      ['la poésie', 'поэзия'],
      ['l\'écrivain', 'писатель'],
      ['l\'auteur', 'автор'],
      ['le chapitre', 'глава'],
      ['l\'intrigue', 'сюжет; интрига'],
      ['le personnage', 'персонаж'],
      ['le réalisateur', 'режиссёр'],
      ['l\'acteur', 'актёр'],
      ['la bande-annonce', 'трейлер'],
      ['le compositeur', 'композитор'],
      ['l\'orchestre', 'оркестр'],
      ['le concert', 'концерт'],
      ['le patrimoine', 'наследие'],
      ['le monument', 'памятник'],
      ['le château', 'замок'],
      ['la tradition', 'традиция'],
      ['la coutume', 'обычай'],
      ['créer', 'создавать'],
      ['peindre', 'писать красками'],
      ['exposer', 'выставлять'],
      ['représenter', 'изображать; представлять'],
      ['assister à', 'присутствовать на'],
      ['célèbre', 'знаменитый'],
    ],
  },
  {
    theme: 'Работа и карьера',
    level: 'B1',
    words: [
      ['la carrière', 'карьера'],
      ['l\'emploi', 'работа; занятость'],
      ['le poste', 'должность'],
      ['le contrat', 'договор'],
      ['l\'entretien', 'собеседование'],
      ['la candidature', 'заявка на работу'],
      ['le candidat', 'кандидат'],
      ['le curriculum vitae', 'резюме'],
      ['la lettre de motivation', 'сопроводительное письмо'],
      ['la compétence', 'навык; компетенция'],
      ['l\'expérience', 'опыт'],
      ['la formation', 'обучение; подготовка'],
      ['le stage', 'стажировка'],
      ['le stagiaire', 'стажёр'],
      ['l\'employeur', 'работодатель'],
      ['l\'employé', 'сотрудник'],
      ['le collègue', 'коллега'],
      ['le chef', 'начальник'],
      ['la réunion', 'совещание'],
      ['le projet', 'проект'],
      ['la tâche', 'задача'],
      ['la responsabilité', 'ответственность'],
      ['l\'horaire', 'график'],
      ['les heures supplémentaires', 'сверхурочные'],
      ['le congé', 'отпуск'],
      ['la démission', 'увольнение по собственному'],
      ['le licenciement', 'увольнение'],
      ['la promotion', 'повышение'],
      ['l\'augmentation', 'повышение зарплаты'],
      ['le syndicat', 'профсоюз'],
      ['l\'entreprise', 'компания'],
      ['embaucher', 'нанимать'],
      ['licencier', 'увольнять'],
      ['démissionner', 'увольняться'],
      ['postuler', 'подавать заявку'],
      ['diriger', 'руководить'],
      ['gérer', 'управлять'],
      ['collaborer', 'сотрудничать'],
      ['réussir', 'преуспевать; сдавать'],
      ['échouer', 'терпеть неудачу'],
    ],
  },
  {
    theme: 'Образование',
    level: 'B1',
    words: [
      ['l\'éducation', 'образование'],
      ['l\'école', 'школа'],
      ['le collège', 'средняя школа'],
      ['le lycée', 'лицей; старшая школа'],
      ['l\'université', 'университет'],
      ['la faculté', 'факультет'],
      ['l\'élève', 'ученик'],
      ['l\'étudiant', 'студент'],
      ['le cours', 'занятие; курс'],
      ['la matière', 'учебный предмет'],
      ['l\'emploi du temps', 'расписание'],
      ['le devoir', 'домашнее задание'],
      ['l\'exercice', 'упражнение'],
      ['l\'examen', 'экзамен'],
      ['le concours', 'конкурсный экзамен'],
      ['la note', 'оценка; заметка'],
      ['le bulletin', 'табель'],
      ['le diplôme', 'диплом'],
      ['la licence', 'бакалавриат'],
      ['le master', 'магистратура'],
      ['la bourse', 'стипендия'],
      ['la rentrée', 'начало учебного года'],
      ['les vacances scolaires', 'школьные каникулы'],
      ['la bibliothèque', 'библиотека'],
      ['le manuel', 'учебник'],
      ['le cahier', 'тетрадь'],
      ['la salle de classe', 'класс'],
      ['le tableau', 'доска'],
      ['la connaissance', 'знание'],
      ['la recherche', 'исследование'],
      ['apprendre', 'учить'],
      ['étudier', 'учиться; изучать'],
      ['enseigner', 'преподавать'],
      ['réviser', 'повторять'],
      ['s\'inscrire', 'записываться'],
      ['redoubler', 'оставаться на второй год'],
      ['obtenir', 'получать'],
      ['obligatoire', 'обязательный'],
      ['scolaire', 'школьный'],
    ],
  },
  {
    theme: 'СМИ и новости',
    level: 'B1',
    words: [
      ['les médias', 'СМИ'],
      ['la presse', 'пресса'],
      ['le journal', 'газета'],
      ['le magazine', 'журнал'],
      ['l\'article', 'статья'],
      ['le titre', 'заголовок'],
      ['la une', 'первая полоса'],
      ['la rubrique', 'рубрика'],
      ['le journaliste', 'журналист'],
      ['le reporter', 'репортёр'],
      ['l\'information', 'информация; новость'],
      ['les actualités', 'новости'],
      ['le reportage', 'репортаж'],
      ['l\'interview', 'интервью'],
      ['l\'émission', 'передача'],
      ['la chaîne', 'канал'],
      ['le direct', 'прямой эфир'],
      ['l\'annonce', 'объявление'],
      ['la publicité', 'реклама'],
      ['le rédacteur', 'редактор'],
      ['la source', 'источник'],
      ['la rumeur', 'слух'],
      ['le fait', 'факт'],
      ['l\'événement', 'событие'],
      ['le scandale', 'скандал'],
      ['la censure', 'цензура'],
      ['la liberté de la presse', 'свобода прессы'],
      ['informer', 'информировать'],
      ['annoncer', 'объявлять'],
      ['publier', 'публиковать'],
      ['diffuser', 'транслировать; распространять'],
      ['s\'informer', 'узнавать новости'],
      ['commenter', 'комментировать'],
      ['censurer', 'подвергать цензуре'],
    ],
  },
  {
    theme: 'Наука и технологии',
    level: 'B1',
    words: [
      ['la science', 'наука'],
      ['la technologie', 'технология'],
      ['la recherche', 'исследование'],
      ['le chercheur', 'исследователь'],
      ['l\'expérience', 'эксперимент; опыт'],
      ['la découverte', 'открытие'],
      ['l\'invention', 'изобретение'],
      ['le progrès', 'прогресс'],
      ['l\'innovation', 'нововведение'],
      ['l\'ordinateur', 'компьютер'],
      ['le logiciel', 'программное обеспечение'],
      ['l\'application', 'приложение'],
      ['le fichier', 'файл'],
      ['les données', 'данные'],
      ['le serveur', 'сервер'],
      ['le réseau social', 'социальная сеть'],
      ['l\'utilisateur', 'пользователь'],
      ['l\'intelligence artificielle', 'искусственный интеллект'],
      ['le robot', 'робот'],
      ['l\'écran tactile', 'сенсорный экран'],
      ['la connexion', 'подключение'],
      ['le mot de passe', 'пароль'],
      ['la panne', 'поломка; сбой'],
      ['la mise à jour', 'обновление'],
      ['le brevet', 'патент'],
      ['l\'expérimentation', 'испытание'],
      ['la théorie', 'теория'],
      ['la preuve', 'доказательство'],
      ['télécharger', 'скачивать; загружать'],
      ['installer', 'устанавливать'],
      ['programmer', 'программировать'],
      ['connecter', 'подключать'],
      ['sauvegarder', 'сохранять'],
      ['inventer', 'изобретать'],
      ['développer', 'разрабатывать'],
      ['numérique', 'цифровой'],
      ['virtuel', 'виртуальный'],
    ],
  },
  {
    theme: 'Мнение и аргументация',
    level: 'B1',
    words: [
      ['l\'avis', 'мнение'],
      ['l\'opinion', 'мнение'],
      ['le point de vue', 'точка зрения'],
      ['l\'argument', 'аргумент'],
      ['la raison', 'причина; разум'],
      ['la conséquence', 'следствие'],
      ['la cause', 'причина'],
      ['le but', 'цель'],
      ['l\'exemple', 'пример'],
      ['la preuve', 'доказательство'],
      ['le doute', 'сомнение'],
      ['la certitude', 'уверенность'],
      ['l\'hypothèse', 'гипотеза'],
      ['la conclusion', 'вывод'],
      ['le débat', 'дискуссия'],
      ['le désaccord', 'разногласие'],
      ['le compromis', 'компромисс'],
      ['penser que', 'считать, что'],
      ['croire que', 'полагать, что'],
      ['trouver que', 'находить, что'],
      ['estimer', 'полагать; оценивать'],
      ['considérer', 'считать; рассматривать'],
      ['être d\'accord', 'соглашаться'],
      ['s\'opposer', 'возражать'],
      ['contredire', 'противоречить'],
      ['admettre', 'признавать'],
      ['ajouter', 'добавлять'],
      ['souligner', 'подчёркивать'],
      ['préciser', 'уточнять'],
      ['résumer', 'резюмировать'],
      ['convaincre', 'убеждать'],
      ['douter', 'сомневаться'],
      ['selon', 'согласно; по мнению'],
      ['en revanche', 'зато; напротив'],
      ['cependant', 'однако'],
      ['pourtant', 'тем не менее'],
      ['d\'ailleurs', 'к тому же'],
      ['en effet', 'действительно'],
      ['par contre', 'зато'],
      ['au contraire', 'наоборот'],
    ],
  },
  {
    theme: 'Абстрактные понятия',
    level: 'B1',
    words: [
      ['l\'idée', 'идея'],
      ['la pensée', 'мысль'],
      ['le sens', 'смысл; направление'],
      ['la façon', 'способ'],
      ['le moyen', 'средство'],
      ['la manière', 'манера; способ'],
      ['le problème', 'проблема'],
      ['la solution', 'решение'],
      ['la question', 'вопрос'],
      ['la réponse', 'ответ'],
      ['le choix', 'выбор'],
      ['la décision', 'решение'],
      ['le changement', 'изменение'],
      ['le développement', 'развитие'],
      ['la situation', 'ситуация'],
      ['la condition', 'условие'],
      ['la possibilité', 'возможность'],
      ['le risque', 'риск'],
      ['l\'avantage', 'преимущество'],
      ['l\'inconvénient', 'недостаток'],
      ['la valeur', 'ценность; значение'],
      ['l\'importance', 'важность'],
      ['la différence', 'разница'],
      ['le rapport', 'отношение; связь'],
      ['le niveau', 'уровень'],
      ['le domaine', 'область; сфера'],
      ['l\'effet', 'эффект; воздействие'],
      ['le pouvoir', 'власть; способность'],
      ['la vérité', 'правда'],
      ['le mensonge', 'ложь'],
      ['la réalité', 'реальность'],
      ['le hasard', 'случайность'],
      ['l\'ensemble', 'совокупность'],
      ['la plupart', 'большинство'],
      ['exister', 'существовать'],
      ['dépendre', 'зависеть'],
      ['concerner', 'касаться'],
      ['permettre', 'позволять'],
      ['empêcher', 'мешать; препятствовать'],
      ['entraîner', 'влечь за собой; тренировать'],
    ],
  },
  {
    theme: 'География и страны',
    level: 'B1',
    words: [
      ['la géographie', 'география'],
      ['le monde', 'мир'],
      ['le continent', 'континент'],
      ['le pays', 'страна'],
      ['la région', 'регион'],
      ['la frontière', 'граница'],
      ['la capitale', 'столица'],
      ['la population', 'население'],
      ['le territoire', 'территория'],
      ['la France', 'Франция'],
      ['la Russie', 'Россия'],
      ['l\'Allemagne', 'Германия'],
      ['l\'Espagne', 'Испания'],
      ['l\'Italie', 'Италия'],
      ['l\'Angleterre', 'Англия'],
      ['les États-Unis', 'США'],
      ['la Chine', 'Китай'],
      ['l\'Europe', 'Европа'],
      ['l\'Afrique', 'Африка'],
      ['l\'Asie', 'Азия'],
      ['l\'océan', 'океан'],
      ['la côte', 'побережье'],
      ['l\'île', 'остров'],
      ['le fleuve', 'река (большая)'],
      ['le désert', 'пустыня'],
      ['la vallée', 'долина'],
      ['la colline', 'холм'],
      ['le climat', 'климат'],
      ['le nord', 'север'],
      ['le sud', 'юг'],
      ['l\'est', 'восток'],
      ['l\'ouest', 'запад'],
      ['l\'étranger', 'заграница; иностранец'],
      ['le paysage', 'пейзаж'],
      ['la carte', 'карта'],
      ['la nationalité', 'национальность'],
      ['le drapeau', 'флаг'],
      ['la langue', 'язык'],
      ['situé', 'расположенный'],
      ['entourer', 'окружать'],
    ],
  },
]
